const assert = require('node:assert/strict');
const { chromium } = require(process.env.MUI_PLAYWRIGHT || 'playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.MUI_CHROMIUM });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => { errors.push(error.message); console.error('PAGE ERROR:', error.message); });
    await page.goto(process.env.MUI_TEST_URL || 'http://127.0.0.1:21530/');
    await page.locator('#username').fill('admin');
    await page.locator('#password').fill('admin');
    await page.locator('#login-button').click();
    await page.locator('[data-view="mihomo"]').click();
    await page.locator('[data-mihomo-tab="outbounds"]').click();
    await page.locator('#mihomo-add-outbound').click();
    assert.deepEqual(errors, []);
    const switchInput = async name => {
      await page.getByRole('tab', { name, exact: true }).click();
      await page.locator(name==='YAML'?'#outbound-yaml-panel':'#outbound-form-panel').waitFor({ state: 'visible' });
      await page.waitForFunction(() => !document.querySelector('#outbound-form-tab').disabled);
      assert.equal(await page.locator('#outbound-import-error').isVisible(), false);
    };
    await switchInput('YAML');
    await switchInput('Form');
    assert.equal(await page.locator('#mihomo-outbound-form [name="name"]').inputValue(), '');
    await switchInput('YAML');
    await page.locator('#outbound-apply').click();
    await page.locator('#outbound-import-error').waitFor({ state: 'visible' });
    await switchInput('Form');
    await page.locator('#mihomo-outbound-form [name="name"]').fill('unfinished');
    await switchInput('YAML');
    await switchInput('Form');
    assert.equal(await page.locator('#mihomo-outbound-form [name="name"]').inputValue(), 'unfinished');
    await page.locator('#mihomo-outbound-form [name="type"]').selectOption('vless');
    await page.locator('#mihomo-outbound-form [name="server"]').fill('example.com');
    await page.locator('#mihomo-outbound-form [name="uuid"]').fill('not-a-uuid');
    await switchInput('YAML');
    await switchInput('Form');
    assert.equal(await page.locator('#mihomo-outbound-form [name="uuid"]').inputValue(), 'not-a-uuid');
    assert.deepEqual(await page.locator('#mihomo-outbound-form').evaluate(form=>Array.from(form.elements).filter(field=>field.willValidate&&!field.validity.valid).map(field=>({name:field.name,value:field.value,message:field.validationMessage}))), []);
    await page.locator('#outbound-apply').click();
    await page.locator('#outbound-import-error').waitFor({ state: 'visible' });
    await switchInput('YAML');
    for(const source of ['name: [unfinished', '', 'name: unfinished\ntype: select\nproxies: []\n']){
      await page.locator('#outbound-yaml').fill(source);
      await switchInput('Form');
      await switchInput('YAML');
      assert.equal(await page.locator('#outbound-yaml').inputValue(), source);
    }
    await page.locator('#mihomo-outbound-modal [data-mihomo-close]').first().click();
    await page.locator('#mihomo-add-outbound').click();
    await page.getByRole('tab', { name: 'YAML', exact: true }).click();
    await page.locator('#outbound-yaml-panel').waitFor({ state: 'visible' });
    const importName = 'Browser-import-'+Date.now();
    const uuid = '00000000-0000-0000-0000-000000000001';
    const link = `vless://${uuid}@example.com:443?security=reality&pbk=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&sid=1234&sni=example.com&type=ws&path=%2Fws&host=cdn.example.com#${importName}`;
    await page.locator('#outbound-share-link').fill(link);
    await page.locator('#outbound-parse-link').click();
    await page.waitForFunction(() => document.querySelector('#outbound-yaml').value.includes('reality-opts:'));
    const initial = await page.locator('#outbound-yaml').inputValue();
    assert.match(initial, /tls: true/);
    await page.screenshot({ path: '.runtime-import/outbound-yaml-desktop.png' });
    await page.locator('#outbound-share-link').fill('invalid://link');
    await page.locator('#outbound-parse-link').click();
    await page.locator('#outbound-import-error').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#outbound-yaml').inputValue(), initial);
    await page.locator('#outbound-yaml').fill(initial + '\nsmux:\n  enabled: false\n');
    await page.getByRole('tab', { name: 'Form', exact: true }).click();
    await page.locator('#outbound-form-panel').waitFor({ state: 'visible' });
    await page.locator('#mihomo-outbound-form [name="server"]').fill('changed.example.com');
    await page.getByRole('tab', { name: 'YAML', exact: true }).click();
    await page.locator('#outbound-yaml-panel').waitFor({ state: 'visible' });
    const edited = await page.locator('#outbound-yaml').inputValue();
    assert.match(edited, /changed.example.com/);
    assert.match(edited, /reality-opts:/);
    assert.match(edited, /smux:/);
    await page.locator('#outbound-apply').click();
    await page.locator('#mihomo-outbound-modal').waitFor({ state: 'hidden' });
    await page.locator('#mihomo-save').click();
    await page.waitForFunction(() => document.querySelector('#mihomo-save').disabled);
    await page.reload();
    await page.locator('[data-view="mihomo"]').click();
    await page.locator('[data-mihomo-tab="outbounds"]').click();
    const row = page.locator('#mihomo-outbound-table tr').filter({ hasText: importName });
    await row.locator('[data-outbound-edit]').click();
    await page.locator('#outbound-yaml-panel').waitFor({ state: 'visible' });
    const persisted = await page.locator('#outbound-yaml').inputValue();
    assert.match(persisted, /changed.example.com/);
    assert.match(persisted, /reality-opts:/);
    assert.match(persisted, /smux:/);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '.runtime-import/outbound-yaml-mobile.png' });
    const bounds = await page.locator('#mihomo-outbound-modal .modal-panel').boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390, JSON.stringify(bounds));
    const editorBounds = await page.locator('#outbound-yaml').boundingBox();
    assert.ok(editorBounds.width > 150 && editorBounds.x + editorBounds.width <= 390);
    await page.locator('#mihomo-outbound-modal [data-mihomo-close]').first().click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#mihomo-add-outbound').click();
    await page.getByRole('tab', { name: 'YAML', exact: true }).click();
    await page.locator('#outbound-yaml-panel').waitFor({ state: 'visible' });
    await page.locator('#outbound-yaml').fill(`name: Pick-${importName}\ntype: select\nproxies: [${importName}, DIRECT]\nlazy: false\n`);
    await page.locator('#outbound-apply').click();
    await page.locator('#mihomo-outbound-modal').waitFor({ state: 'hidden' });
    await page.locator('#mihomo-save').click();
    await page.waitForFunction(() => document.querySelector('#mihomo-save').disabled);
    await page.locator('#mihomo-add-outbound').click();
    await page.locator('#mihomo-outbound-form [name="name"]').fill('Form-'+importName);
    await page.locator('#mihomo-outbound-form [name="server"]').fill('example.com');
    await page.locator('#mihomo-outbound-form [name="password"]').fill('form-test-secret');
    await page.locator('#outbound-apply').click();
    await page.locator('#mihomo-outbound-modal').waitFor({ state: 'hidden' });
    await page.locator('#mihomo-add-outbound').click();
    await page.getByRole('tab', { name: 'YAML', exact: true }).click();
    await page.locator('#outbound-yaml-panel').waitFor({ state: 'visible' });
    await page.locator('#outbound-yaml').fill('name: [broken');
    await page.locator('#outbound-apply').click();
    await page.locator('#outbound-import-error').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#outbound-yaml').inputValue(), 'name: [broken');
    await page.locator('#outbound-yaml').fill(`proxies:\n- {name: Batch-${importName}, type: socks5, server: example.com, port: 1080}\nproxy-groups:\n- name: BatchGroup-${importName}\n  type: select\n  proxies: [Batch-${importName}, DIRECT]\n`);
    await page.locator('#outbound-apply').click();
    await page.locator('#mihomo-outbound-modal').waitFor({ state: 'hidden' });
    await page.locator('#mihomo-save').click();
    await page.waitForFunction(() => document.querySelector('#mihomo-save').disabled);
    assert.deepEqual(errors, []);
    console.log('PASS: empty/incomplete draft tab navigation, validation on Apply, preserved YAML, link conversion, persistence, draft group references, desktop/mobile layout');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
