const assert = require('node:assert/strict');
const { chromium } = require(process.env.MUI_PLAYWRIGHT || 'playwright');

(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.MUI_CHROMIUM});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    const base=process.env.MUI_WARP_TEST_URL||'http://127.0.0.1:21540';
    await page.goto(base+'/');
    await page.locator('#username').fill('admin');await page.locator('#password').fill('admin');await page.locator('#login-button').click();
    await page.locator('[data-view="mihomo"]').click();
    await page.locator('.basics-section>summary').filter({hasText:'Basic Routing'}).click();
    await page.locator('#basics-warp').click();
    await page.waitForFunction(()=>!document.querySelector('#warp-create').disabled);
    assert.equal(await page.locator('#warp-empty').isVisible(),true);
    await page.screenshot({path:'.runtime-import/warp-empty.png'});
    await page.locator('#warp-close').click();
    await page.locator('[data-mihomo-tab="outbounds"]').click();
    await page.locator('#mihomo-warp').click();
    await page.waitForFunction(()=>!document.querySelector('#warp-create').disabled);
    await page.locator('#warp-create').click();
    await page.locator('#warp-details').waitFor({state:'visible'});
    assert.equal(await page.locator('#warp-access-token').textContent(),'test-access-token');
    assert.equal(Buffer.from(await page.locator('#warp-private-key').textContent(),'base64').length,32);
    assert.equal(await page.locator('#warp-outbound-status').textContent(),'Disabled');
    await page.locator('#warp-refresh').click();
    await page.waitForFunction(()=>!document.querySelector('#warp-refresh').disabled);
    await page.locator('.warp-license>summary').click();
    await page.locator('#warp-license-input').fill('bad');assert.equal(await page.locator('#warp-license-update').isEnabled(),false);
    await page.locator('#warp-license-input').fill('rejected-eeeeeeee-ffffffff');
    await page.locator('#warp-license-update').click();await page.locator('#warp-error').waitFor({state:'visible'});
    assert.equal(await page.locator('#warp-license-value').textContent(),'aaaaaaaa-bbbbbbbb-cccccccc');
    await page.locator('#warp-license-input').fill('dddddddd-eeeeeeee-ffffffff');
    await page.locator('#warp-license-update').click();
    await page.waitForFunction(()=>document.querySelector('#warp-account-type').textContent==='unlimited');
    await page.screenshot({path:'.runtime-import/warp-account-desktop.png'});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'.runtime-import/warp-account-mobile.png'});
    const bounds=await page.locator('.warp-modal').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);
    const overflow=await page.locator('.warp-modal').evaluate(el=>el.scrollWidth>el.clientWidth);assert.equal(overflow,false);
    await page.setViewportSize({width:1440,height:1050});
    await page.locator('#warp-add').click();await page.locator('#warp-modal').waitFor({state:'hidden'});
    assert.ok((await page.locator('#mihomo-outbound-table').textContent()).includes('wireguard'));
    await page.locator('[data-mihomo-tab="basics"]').click();
    assert.equal(await page.locator('#basics-warp').isVisible(),false);
    await page.locator('#basics-warpDomains-input').fill('example.com');await page.locator('#basics-warpDomains-input').press('Enter');
    await page.locator('#mihomo-save').click();await page.waitForFunction(()=>document.querySelector('#mihomo-save').disabled);
    let config=(await (await page.request.get(base+'/api/raw-config')).json()).data.config;
    assert.ok(config.includes('DOMAIN-SUFFIX,example.com,warp'));
    assert.ok(config.includes('reserved:'));
    const snapshot=(await (await page.request.get(base+'/api/state')).json()).data.state;
    assert.equal(snapshot.warp,undefined);assert.ok(snapshot.outbounds[0].warpDeviceId);
    await page.reload();await page.locator('[data-view="mihomo"]').click();await page.locator('[data-mihomo-tab="outbounds"]').click();
    await page.locator('[data-outbound-edit]').click();await page.locator('#outbound-yaml-panel').waitFor({state:'visible'});
    let yaml=await page.locator('#outbound-yaml').inputValue();
    yaml=yaml.replace('name: "warp"','name: "renamed-warp"').replace('engage.cloudflareclient.com','changed.example.com');
    await page.locator('#outbound-yaml').fill(yaml);await page.locator('#outbound-apply').click();await page.locator('#mihomo-outbound-modal').waitFor({state:'hidden'});
    await page.locator('#mihomo-save').click();await page.waitForFunction(()=>document.querySelector('#mihomo-save').disabled);
    config=(await (await page.request.get(base+'/api/raw-config')).json()).data.config;assert.ok(config.includes('DOMAIN-SUFFIX,example.com,renamed-warp'));
    await page.locator('#mihomo-warp').click();await page.waitForFunction(()=>!document.querySelector('#warp-refresh').disabled);
    assert.equal(await page.locator('#warp-outbound-status').textContent(),'Enabled');
    assert.equal(await page.locator('#warp-add').textContent(),'Reset Outbound');
    await page.locator('#warp-add').click();await page.locator('#warp-modal').waitFor({state:'hidden'});
    await page.locator('#mihomo-save').click();await page.waitForFunction(()=>document.querySelector('#mihomo-save').disabled);
    config=(await (await page.request.get(base+'/api/raw-config')).json()).data.config;
    assert.ok(config.includes('name: "renamed-warp"'));assert.ok(config.includes('engage.cloudflareclient.com'));assert.ok(!config.includes('changed.example.com'));
    await page.locator('#mihomo-warp').click();await page.waitForFunction(()=>!document.querySelector('#warp-delete').disabled);
    page.once('dialog',dialog=>dialog.accept());await page.locator('#warp-delete').click();await page.locator('#warp-empty').waitFor({state:'visible'});
    await page.locator('#warp-close').click();await page.locator('#mihomo-save').click();await page.waitForFunction(()=>document.querySelector('#mihomo-save').disabled);
    await page.locator('[data-mihomo-tab="basics"]').click();
    await page.locator('.basics-section>summary').filter({hasText:'Basic Routing'}).click();
    assert.equal(await page.locator('#basics-warp').isVisible(),true);assert.equal(await page.locator('#basics-warpDomains-input').isVisible(),false);
    const account=(await (await page.request.get(base+'/api/mihomo/warp')).json()).data.account;assert.equal(account,null);
    config=(await (await page.request.get(base+'/api/raw-config')).json()).data.config;assert.ok(!config.includes('wireguard'));assert.ok(!config.includes('DOMAIN-SUFFIX,example.com'));
    assert.deepEqual(errors,[]);
    console.log('PASS: shared WARP modal, create, refresh, license failure/success, native WireGuard, Basics routing, persistence, rename/reset, local delete, responsive layout');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
