package app

// 订阅模版的服务端提示。和其它功能一样走 translateMessage：带参数的提示都把参数
// 放在 ": " 之后，所以这里只登记参数前的那一段。
//
// 顺序：en, zh-TW, ja, ru, fa, vi, es, tr, uk, pt-BR。
var subTemplateMessages = map[string][10]string{
	"订阅模版文件无效":                   {"The subscription template file is invalid", "訂閱範本檔案無效", "サブスクリプションテンプレートファイルが無効です", "Файл шаблонов подписки повреждён", "فایل الگوی اشتراک نامعتبر است", "Tệp mẫu đăng ký không hợp lệ", "El archivo de plantillas de suscripción no es válido", "Abonelik şablonu dosyası geçersiz", "Файл шаблонів підписки пошкоджено", "O arquivo de modelos de assinatura é inválido"},
	"不支持的订阅模版文件版本":               {"Unsupported subscription template file version", "不支援的訂閱範本檔案版本", "サポートされていないテンプレートファイルのバージョン", "Неподдерживаемая версия файла шаблонов", "نسخهٔ فایل الگو پشتیبانی نمی‌شود", "Phiên bản tệp mẫu không được hỗ trợ", "Versión del archivo de plantillas no compatible", "Desteklenmeyen şablon dosyası sürümü", "Непідтримувана версія файлу шаблонів", "Versão do arquivo de modelos não suportada"},
	"订阅模版数量超过上限":                 {"Too many subscription templates", "訂閱範本數量超過上限", "テンプレートの数が上限を超えています", "Слишком много шаблонов подписки", "تعداد الگوهای اشتراک از حد مجاز بیشتر است", "Quá nhiều mẫu đăng ký", "Demasiadas plantillas de suscripción", "Abonelik şablonu sayısı sınırı aştı", "Забагато шаблонів підписки", "Modelos de assinatura demais"},
	"订阅模版 ID 无效":                 {"Invalid subscription template ID", "訂閱範本 ID 無效", "テンプレート ID が無効です", "Недопустимый ID шаблона", "شناسهٔ الگو نامعتبر است", "ID mẫu không hợp lệ", "ID de plantilla no válido", "Geçersiz şablon kimliği", "Недійсний ID шаблону", "ID de modelo inválido"},
	"订阅模版无效":                     {"Invalid subscription template", "訂閱範本無效", "テンプレートが無効です", "Недопустимый шаблон подписки", "الگوی اشتراک نامعتبر است", "Mẫu đăng ký không hợp lệ", "Plantilla de suscripción no válida", "Geçersiz abonelik şablonu", "Недійсний шаблон підписки", "Modelo de assinatura inválido"},
	"模版内容为空":                     {"The template is empty", "範本內容為空", "テンプレートが空です", "Шаблон пуст", "الگو خالی است", "Mẫu đang trống", "La plantilla está vacía", "Şablon boş", "Шаблон порожній", "O modelo está vazio"},
	"模版超过 2 MB":                  {"The template is larger than 2 MB", "範本超過 2 MB", "テンプレートが 2 MB を超えています", "Шаблон больше 2 МБ", "حجم الگو بیش از 2 مگابایت است", "Mẫu lớn hơn 2 MB", "La plantilla supera los 2 MB", "Şablon 2 MB'tan büyük", "Шаблон більший за 2 МБ", "O modelo tem mais de 2 MB"},
	"YAML 解析失败":                  {"YAML parsing failed", "YAML 解析失敗", "YAML の解析に失敗しました", "Ошибка разбора YAML", "تجزیهٔ YAML ناموفق بود", "Phân tích YAML thất bại", "Error al analizar el YAML", "YAML ayrıştırılamadı", "Помилка розбору YAML", "Falha ao analisar o YAML"},
	"不是 Mihomo 配置：顶层必须是键值映射":     {"Not a Mihomo config: the top level must be a key/value mapping", "不是 Mihomo 設定：頂層必須是鍵值對應", "Mihomo の設定ではありません：最上位はキーと値のマッピングである必要があります", "Это не конфигурация Mihomo: верхний уровень должен быть сопоставлением ключей и значений", "پیکربندی Mihomo نیست: سطح بالا باید نگاشت کلید و مقدار باشد", "Không phải cấu hình Mihomo: cấp cao nhất phải là ánh xạ khóa/giá trị", "No es una configuración de Mihomo: el nivel superior debe ser un mapa de claves y valores", "Mihomo yapılandırması değil: en üst düzey anahtar/değer eşlemesi olmalı", "Це не конфігурація Mihomo: верхній рівень має бути зіставленням ключів і значень", "Não é uma configuração Mihomo: o nível superior deve ser um mapa de chaves e valores"},
	"缺少 proxy-groups 分组":         {"proxy-groups is missing", "缺少 proxy-groups 分組", "proxy-groups がありません", "Отсутствует proxy-groups", "proxy-groups وجود ندارد", "Thiếu proxy-groups", "Falta proxy-groups", "proxy-groups eksik", "Відсутній proxy-groups", "proxy-groups está ausente"},
	"proxy-groups 里有缺少 name 的分组": {"A group in proxy-groups has no name", "proxy-groups 裡有缺少 name 的分組", "proxy-groups に name のないグループがあります", "В proxy-groups есть группа без name", "یکی از گروه‌های proxy-groups فیلد name ندارد", "Một nhóm trong proxy-groups không có name", "Un grupo de proxy-groups no tiene name", "proxy-groups içinde name alanı olmayan bir grup var", "У proxy-groups є група без name", "Um grupo em proxy-groups não tem name"},
	"分组名重复":                      {"Duplicate group name", "分組名稱重複", "グループ名が重複しています", "Повторяющееся имя группы", "نام گروه تکراری است", "Tên nhóm bị trùng", "Nombre de grupo duplicado", "Yinelenen grup adı", "Повторювана назва групи", "Nome de grupo duplicado"},
	"缺少 rules 规则":                {"rules is missing", "缺少 rules 規則", "rules がありません", "Отсутствует rules", "rules وجود ندارد", "Thiếu rules", "Falta rules", "rules eksik", "Відсутній rules", "rules está ausente"},
	"rules 里有不是字符串的规则":           {"A rule in rules is not a string", "rules 裡有不是字串的規則", "rules に文字列ではないルールがあります", "В rules есть правило, которое не является строкой", "یکی از قوانین rules رشته نیست", "Một quy tắc trong rules không phải chuỗi", "Una regla de rules no es una cadena", "rules içinde metin olmayan bir kural var", "У rules є правило, яке не є рядком", "Uma regra em rules não é texto"},
	"规则指向节点，但没有可放节点的分组":          {"A rule points at a node, but no group receives nodes", "規則指向節點，但沒有可放節點的分組", "ルールがノードを指していますが、ノードを受け取るグループがありません", "Правило указывает на узел, но ни одна группа не получает узлы", "یک قانون به یک گره اشاره می‌کند، اما هیچ گروهی گره دریافت نمی‌کند", "Một quy tắc trỏ tới nút nhưng không có nhóm nào nhận nút", "Una regla apunta a un nodo, pero ningún grupo recibe nodos", "Bir kural bir düğümü gösteriyor ama hiçbir grup düğüm almıyor", "Правило вказує на вузол, але жодна група не отримує вузли", "Uma regra aponta para um nó, mas nenhum grupo recebe nós"},
	"模版里不能包含节点":                  {"A template cannot contain nodes", "範本裡不能包含節點", "テンプレートにノードを含めることはできません", "Шаблон не может содержать узлы", "الگو نمی‌تواند گره داشته باشد", "Mẫu không được chứa nút", "Una plantilla no puede contener nodos", "Şablon düğüm içeremez", "Шаблон не може містити вузли", "Um modelo não pode conter nós"},
	"模版名称不能为空":                   {"The template name cannot be empty", "範本名稱不能為空", "テンプレート名を入力してください", "Имя шаблона не может быть пустым", "نام الگو نمی‌تواند خالی باشد", "Tên mẫu không được để trống", "El nombre de la plantilla no puede estar vacío", "Şablon adı boş olamaz", "Назва шаблону не може бути порожньою", "O nome do modelo não pode ficar vazio"},
	"模版名称不能超过 64 个字符":            {"The template name cannot exceed 64 characters", "範本名稱不能超過 64 個字元", "テンプレート名は 64 文字以内にしてください", "Имя шаблона не может превышать 64 символа", "نام الگو نمی‌تواند بیش از 64 نویسه باشد", "Tên mẫu không được quá 64 ký tự", "El nombre de la plantilla no puede superar los 64 caracteres", "Şablon adı 64 karakteri aşamaz", "Назва шаблону не може перевищувати 64 символи", "O nome do modelo não pode passar de 64 caracteres"},
	"未知的模版变体":                    {"Unknown template variant", "未知的範本變體", "不明なテンプレートのバリアントです", "Неизвестный вариант шаблона", "نوع الگو ناشناخته است", "Biến thể mẫu không xác định", "Variante de plantilla desconocida", "Bilinmeyen şablon çeşidi", "Невідомий варіант шаблону", "Variante de modelo desconhecida"},
	"规则格式无效":                     {"Invalid rule format", "規則格式無效", "ルールの形式が無効です", "Неверный формат правила", "قالب قانون نامعتبر است", "Định dạng quy tắc không hợp lệ", "Formato de regla no válido", "Geçersiz kural biçimi", "Неправильний формат правила", "Formato de regra inválido"},
	"分组名缺失或重复":                   {"Group name missing or duplicated", "分組名稱缺失或重複", "グループ名がないか重複しています", "Имя группы отсутствует или повторяется", "نام گروه وجود ندارد یا تکراری است", "Tên nhóm bị thiếu hoặc trùng", "Nombre de grupo ausente o duplicado", "Grup adı eksik veya yinelenmiş", "Назва групи відсутня або повторюється", "Nome de grupo ausente ou duplicado"},
	"分组缺少 type":                  {"Group has no type", "分組缺少 type", "グループに type がありません", "У группы нет type", "گروه type ندارد", "Nhóm không có type", "El grupo no tiene type", "Grubun type alanı yok", "Група не має type", "O grupo não tem type"},
	"分组的 proxies 必须是列表":          {"A group's proxies must be a list", "分組的 proxies 必須是清單", "グループの proxies はリストである必要があります", "proxies группы должен быть списком", "proxies گروه باید فهرست باشد", "proxies của nhóm phải là danh sách", "El campo proxies del grupo debe ser una lista", "Grubun proxies alanı liste olmalı", "proxies групи має бути списком", "O campo proxies do grupo deve ser uma lista"},
	"分组引用了不存在的分组或节点":             {"A group references a missing group or node", "分組引用了不存在的分組或節點", "グループが存在しないグループまたはノードを参照しています", "Группа ссылается на несуществующую группу или узел", "یک گروه به گروه یا گرهٔ ناموجود ارجاع می‌دهد", "Nhóm tham chiếu tới nhóm hoặc nút không tồn tại", "Un grupo hace referencia a un grupo o nodo inexistente", "Bir grup var olmayan bir grubu veya düğümü kullanıyor", "Група посилається на неіснуючу групу або вузол", "Um grupo referencia um grupo ou nó inexistente"},
	"分组是空的":                      {"Group is empty", "分組是空的", "グループが空です", "Группа пуста", "گروه خالی است", "Nhóm đang trống", "El grupo está vacío", "Grup boş", "Група порожня", "O grupo está vazio"},
	"规则指向不存在的分组":                 {"A rule points at a missing group", "規則指向不存在的分組", "ルールが存在しないグループを指しています", "Правило указывает на несуществующую группу", "یک قانون به گروه ناموجود اشاره می‌کند", "Quy tắc trỏ tới nhóm không tồn tại", "Una regla apunta a un grupo inexistente", "Bir kural var olmayan bir grubu gösteriyor", "Правило вказує на неіснуючу групу", "Uma regra aponta para um grupo inexistente"},
	"备份中的订阅模版无效":                 {"The subscription templates in the backup are invalid", "備份中的訂閱範本無效", "バックアップ内のテンプレートが無効です", "Шаблоны подписки в резервной копии недействительны", "الگوهای اشتراک در نسخهٔ پشتیبان نامعتبرند", "Mẫu đăng ký trong bản sao lưu không hợp lệ", "Las plantillas de suscripción de la copia de seguridad no son válidas", "Yedekteki abonelik şablonları geçersiz", "Шаблони підписки в резервній копії недійсні", "Os modelos de assinatura do backup são inválidos"},
	"订阅模版恢复失败":                   {"Restoring subscription templates failed", "訂閱範本恢復失敗", "テンプレートの復元に失敗しました", "Не удалось восстановить шаблоны подписки", "بازیابی الگوهای اشتراک ناموفق بود", "Khôi phục mẫu đăng ký thất bại", "No se pudieron restaurar las plantillas de suscripción", "Abonelik şablonları geri yüklenemedi", "Не вдалося відновити шаблони підписки", "Falha ao restaurar os modelos de assinatura"},
}

func init() {
	languages := []string{"zh-TW", "ja", "ru", "fa", "vi", "es", "tr", "uk", "pt-BR"}
	for source, translations := range subTemplateMessages {
		messagesEN[source] = translations[0]
		for i, language := range languages {
			messagesLocalized[language][source] = translations[i+1]
		}
	}
}
